; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "EliteSmile"
#define MyAppVersion "1.5"
#define MyAppPublisher "Hashem Ameen"
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "EliteSmile.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".exe"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{3EF138E7-B7B6-4529-8CD6-234C73A96147}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
; DefaultDirName={autopf}\EliteSmile
DefaultDirName=C:\EliteSmile
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
; ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
; ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=EliteSmileSetup
OutputDir=C:\Users\AL-HASHEM\Desktop\Output
SetupIconFile=C:\Users\AL-HASHEM\Desktop\EliteSmile\Icons\App\add_new_dental.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "arabic"; MessagesFile: "compiler:Languages\Arabic.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Source: "C:\Program Files (x86)\Inno Setup 6\Examples\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\AL-HASHEM\Desktop\EliteSmile\EliteSmile\bin\Debug\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\AL-HASHEM\Desktop\EliteSmile\EliteSmile\bin\Debug\DataBase.db"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\AL-HASHEM\Desktop\EliteSmile\EliteSmile\bin\Debug\EliteSmile.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\AL-HASHEM\Desktop\EliteSmile\EliteSmile\bin\Debug\EliteSmile.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\AL-HASHEM\Desktop\EliteSmile\EliteSmile\bin\Debug\EliteSmile.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\AL-HASHEM\Desktop\EliteSmile\EliteSmile\bin\Debug\EliteSmile.vshost.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\AL-HASHEM\Desktop\EliteSmile\EliteSmile\bin\Debug\EliteSmile.vshost.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\AL-HASHEM\Desktop\EliteSmile\EliteSmile\bin\Debug\EliteSmile.vshost.exe.manifest"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\AL-HASHEM\Desktop\EliteSmile\EliteSmile\bin\Debug\query.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\AL-HASHEM\Desktop\EliteSmile\EliteSmile\bin\Debug\System.Data.SQLite.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

